server:
  port: 7070
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounting_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: accounting
    password: acc1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
