version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: accounting_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: accounting_db
      MYSQL_USER: accounting
      MYSQL_PASSWORD: acc1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: